### ISSUE TITLE
plz.. help me

### ISSUE THREAD

**Issue by ONNONS** [DNQuAng10/YOLOv5_Deepstream_6.0#4]
I am difficult to practice your tutorial I am a high school student so it is difficult to understand Please explain in an easy way

**Comment by DNQuAng10** [comment]
Hi @ONNONS , Did you read all README.md ? where do you not understand ?

**Comment by DNQuAng10** [comment]
If you have any trouble, you should comment to this issues, I will trying answer soon...

**Comment by ONNONS** [comment]
Setup Deepstream Triton Docker 

"deepstream:6.0-triton" Where do I download this?

**Comment by ONNONS** [comment]
I tried entering your code

Do I have to enter a code while downloading individually?

**Comment by DNQuAng10** [comment]
You use Window, Linux or Mac? Do you know Docker ?

**Comment by DNQuAng10** [comment]
the first, you need to Docker. You can see tutorial for install docker by this link: https://docs.docker.com/get-docker/

**Comment by DNQuAng10** [comment]
Do your computer have GPU ? If you don't, you can't run my project. DeepStream require at least one GPU. This project don't run on Google Colab too.

**Comment by ONNONS** [comment]
i have a jetsonnano !

**Comment by DNQuAng10** [comment]
Oh, good... I think,  you are just starting to learn about computer vision?

**Comment by ONNONS** [comment]
Yes! I'm very interested in your github and would love to see it run, but I'm stupid...T_T

**Comment by DNQuAng10** [comment]
Don't worry about that. Anybody start from zero. You can see the result of my project at link: https://drive.google.com/file/d/1ISmwFe6ezzrMMtRtsoZvUUn9HPmbBnIm/view?usp=sharing.

**Comment by ONNONS** [comment]
It's a great skill!
Can you show us the contents of your GitHub in a video from start to finish? If possible, I want to give you a present someday.

**Comment by DNQuAng10** [comment]
This nice idea. If you like computer vision, I suggest you should work to Yolov5 before start DeepStream Triton Yolov5. DeepStream and Triton is toolkit and framework for accelerator inference. There are advance technical and it really hard for beginner. You absolutely reached result like video by simple method: OpenCV + Yolov5.

**Comment by DNQuAng10** [comment]
You can start to Yolov5 now: https://github.com/ultralytics/yolov5

**Comment by ONNONS** [comment]
yolov5 practice was easy to follow because there were many materials on YouTube, but jetsonNano + Deepstream6.0 + yolov5 seems really difficult. I thought about giving up... I keep thinking about it... The way I succeed...

**Comment by ONNONS** [comment]
Thank you so much for taking the time to answer... I'm so thankful for you. I look forward to studying more and visiting your github again.

**Comment by DNQuAng10** [comment]
Thank you too, bro.
